services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
