"""Initial migration - FactGameEvent table

Revision ID: d48e75bbe6fe
Revises:
Create Date: 2026-06-06 23:24:14.530682

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d48e75bbe6fe"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact_game_events",
        sa.Column(
            "id",
            sa.String(length=30),
            nullable=False,
            comment="Unique game identifier from source API",
        ),
        sa.Column("league_id", sa.String(length=2), nullable=False, comment="League identifier"),
        sa.Column(
            "season_id",
            sa.Integer(),
            nullable=False,
            comment="Season identifier, the start year of the season",
        ),
        sa.Column(
            "season_stage_id",
            sa.Integer(),
            nullable=False,
            comment="Identifier of the stage during the season for the game",
        ),
        sa.Column(
            "round_number",
            sa.Integer(),
            nullable=False,
            comment="Round number for elimination tournaments, 0 means no rounds",
        ),
        sa.Column(
            "series_index",
            sa.Integer(),
            nullable=False,
            comment="Series index within the round, 0-based, resets for each round",
        ),
        sa.Column(
            "schedule_id",
            sa.Integer(),
            nullable=False,
            comment="Internal scheduling identifier of the game, not sequential properly",
        ),
        sa.Column(
            "game_datetime",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Game start time in UTC",
        ),
        sa.Column(
            "status_id",
            sa.Integer(),
            nullable=False,
            comment="Game status: 1=not started, 2=in progress, 3=completed",
        ),
        sa.Column(
            "period_count",
            sa.Integer(),
            nullable=False,
            comment="Current period number (e.g., 1-4 for regulation, 5+ for overtime)",
        ),
        sa.Column(
            "away_team_id", sa.Integer(), nullable=False, comment="Away team unique identifier"
        ),
        sa.Column(
            "away_team_tricode",
            sa.String(length=10),
            nullable=False,
            comment="Away team 3-letter abbreviation code",
        ),
        sa.Column(
            "away_team_name", sa.String(length=100), nullable=False, comment="Away team full name"
        ),
        sa.Column(
            "away_team_city", sa.String(length=100), nullable=True, comment="Away team city name"
        ),
        sa.Column(
            "away_team_score", sa.Integer(), nullable=False, comment="Away team current score"
        ),
        sa.Column(
            "home_team_id", sa.Integer(), nullable=False, comment="Home team unique identifier"
        ),
        sa.Column(
            "home_team_tricode",
            sa.String(length=10),
            nullable=False,
            comment="Home team 3-letter abbreviation code",
        ),
        sa.Column(
            "home_team_name", sa.String(length=100), nullable=False, comment="Home team full name"
        ),
        sa.Column(
            "home_team_city", sa.String(length=100), nullable=True, comment="Home team city name"
        ),
        sa.Column(
            "home_team_score", sa.Integer(), nullable=False, comment="Home team current score"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment=(
            "Fact table for basketball game events. "
            "Stores basic metadata, e.g. team participants, and scoring outcomes."
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_game_events")
    # ### end Alembic commands ###
